name: Generate SmartDNS Config

on:
  schedule:
    - cron: '0 0,12 * * *'
  push:
    branches:
      - main

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download hosts file
      run: wget -O next-hosts.txt https://gitlab.com/ineo6/hosts/-/raw/master/next-hosts

    - name: Run conversion script and save to next-hosts.conf
      run: |
        chmod +x convert_hosts_to_smartdns.sh
        ./convert_hosts_to_smartdns.sh > next-hosts.conf
      working-directory: ${{ github.workspace }}

    - name: Update time in SmartDNS config
      run: |
        sed -i "1s/.*/# Generated at: $(date '+%Y-%m-%d %H:%M:%S')/" next-hosts.conf
      working-directory: ${{ github.workspace }}

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add next-hosts.conf
        git commit -m "Update SmartDNS config" || true
        git push
